### ISSUE TITLE
Figure out which design elements need to be customisable

### ISSUE THREAD

**Issue by katjam** [neontribe/contemplating-action#1]

**Comment by HedgehogHolly** [comment]
I have created a RTB and analysed what I think Charities may want to change. Some of the suggestions may be allowing them too much customisation and can be disregarded.

[RealTimeBoard - Customising Design Elements](https://realtimeboard.com/app/board/o9J_kyLGU0c=/)

**Typography** is obviously one of the biggest things they will want to change: typeface, size, colour being the main changes. Hover text effects like underline and there are some places where they might want to change the alignment of the text.

**Colour** changes for the buttons/icons, type, general background colours. Also the ability to change the colours on hover effects.

**Icons** will need to change for the information sections but some charities might also want to change or remove icons in the email buttons or headers.

**General** observations - Charities might want to change the border radius of the information sections or buttons so they are not as rounded. Charities might want the option to display multiple images on the front page, a carousel/slideshow of the story images rather than one static image.



Also, I'm not sure if this is helpful but I did do a RTB of general design comments for Haven a while ago

[RealTimeBoard - Haven Design Comments](https://realtimeboard.com/app/board/o9J_kyqrKAU=/)

**Comment by katjam** [comment]
@HedgehogHolly I can't see the realtime boards but your comments are exactly what I was after. Thanks.

I'll have a look and see how easy it would be to alter all of those without changing the code too much. I imagine if we move the css selectors we think we want to customise into a separate file (or even section) with clear documentation that could be sufficient for this round. We might even be able to create a document which visually connects the css with examples in situ of the thing it alters (if that's useful)

**Comment by katjam** [comment]
If you are happy with this. You can close. (but please fix the realtime links - I think the haven one is wrong and the other is private)

**Comment by HedgehogHolly** [comment]
@katjam I believe I've fixed the links and they should no longer be private. 

I happy to close this.
