### ISSUE TITLE
Blog post/ pdf/ visual overview of project

### ISSUE THREAD

**Issue by katjam** [neontribe/contemplating-action#25]
## Description
This is 'advertising' materials for the demo site that we can use for approaching charities.
@katquatermass or @HedgehogHolly Probably know what needs doing.

## Plan
- [ ]  Including #10 
- [ ] TBC

**Comment by katquatermass** [comment]
Yes - current next steps are with @HedgehogHolly  I can do copy and update/critique visual work on 12th or 13th Feb

**Comment by HedgehogHolly** [comment]
Is this enough arrows? and are you happy with the icons I used?

![pathway-100](https://user-images.githubusercontent.com/41140803/52470642-ad9efa80-2b86-11e9-9527-553767413a33.jpg)

**Comment by HedgehogHolly** [comment]
I've taken a stab at something for contemplating cycles, let me know if its what you were thinking @katquatermass 


![artboard 5-100](https://user-images.githubusercontent.com/41140803/52472182-8ea26780-2b8a-11e9-8f03-32f964678bd5.jpg)

**Comment by katquatermass** [comment]
Yes I'm really liking this. I think it might need arrows around it to emphasise that it waves in and out  around the cycle - but I'm not wedded to that.  And I think the icons needs words with them - as ever icons make it look more creative and signal something with a look but we need the full signifier from the phrases too.   (the icon for the final version is chat bubble and telephone receiver as our action in any situation is Reach out for support.)

 I'd still like to see what happens when the longer form text is put in some how - I know it'll get busy but I want to see visually how busy. I had a couple of ideas for how on the last mockup which probably don't work with the full circles (which I like more) - On this variant I think it might be spider leg to another circle outline colour and black text? It'll mean needing more space between the three examples and our central one, but its worth a try?

**Comment by katquatermass** [comment]
> Is this enough arrows? and are you happy with the icons I used?
> 
> ![pathway-100](https://user-images.githubusercontent.com/41140803/52470642-ad9efa80-2b86-11e9-9527-553767413a33.jpg)

YES - like the icons. I think arrows along the top strip will help with continuity but on pure does it work level the ones you've got are the essential ones

**Comment by HedgehogHolly** [comment]
>I think it might need arrows around it to emphasise that it waves in and out around the cycle

![artboard 5-100](https://user-images.githubusercontent.com/41140803/52489542-6f233300-2bba-11e9-94cd-18abc8c623ac.jpg)

>I'd still like to see what happens when the longer form text is put in some how

I can make one with long form text and see what it looks like

**Comment by katquatermass** [comment]
Yes! I like. Thank you!

**Comment by HedgehogHolly** [comment]
@katquatermass this is a version with the long form text, what do you think?

![stages-of-change](https://user-images.githubusercontent.com/41140803/52555741-7fb5f200-2de2-11e9-8af0-efbd9199d866.jpg)

**Comment by katquatermass** [comment]
I like and will use both of these versions @HedgehogHolly  either on train home today or Monday I will go through the long form text and cut down those that are super long... where is best place to do that - in the google doc or do you want to use some kind of pdf viewer that'll let me drop comments onto the images?


Also - since we'll be using them in the same context - can you bring the other one that shows the journey with the app - the green one  - into the same brand colours and fonts as this?

**Comment by katquatermass** [comment]
I'll aim to do the actual blog from this as one of my first tasks in Monday if I can

**Comment by HedgehogHolly** [comment]
@katquatermass google docs would probably be best to change the long copy.  I will change the other journey app to the brand colours as well.

**Comment by katjam** [comment]
@HedgehogHolly :heart_eyes:

**Comment by HedgehogHolly** [comment]
![pathway-purple](https://user-images.githubusercontent.com/41140803/52848575-003c6180-3107-11e9-8fb8-91ee4b130723.jpg)

**Comment by HedgehogHolly** [comment]
I just remembered when I did the mock-up of the app that the teal doesn't work for accessibility reasons. So I've changed them all to the pink, is that okay? @katquatermass 

![stages of change-05](https://user-images.githubusercontent.com/41140803/52849478-07646f00-3109-11e9-8786-98acc620c953.jpg)
![stages of change-06](https://user-images.githubusercontent.com/41140803/52849482-09c6c900-3109-11e9-8f2e-21a1bf2671df.jpg)
![pathway-purple_pathway](https://user-images.githubusercontent.com/41140803/52849515-206d2000-3109-11e9-98fb-a52767f6b609.jpg)

**Comment by HedgehogHolly** [comment]
Kat wasn't too sure on the pink colour, the other two accessible colour within the blue/teal shades are these:

![screenshot 2019-02-18 at 14 55 11](https://user-images.githubusercontent.com/41140803/52959052-499de280-338d-11e9-811c-d913d3545fcd.png)

@katjam do you have a preference or do you think the pink is alright?

**Comment by katjam** [comment]
@hedgehogholly I think pink was ok but maybe this blue (on the right) more neutral. It's hard to decide we want serious/ trustworthy/friendly/gentle to come across I think.

**Comment by katquatermass** [comment]
For me, the pink becomes an issue because some of the things we are looking
at are women's specific and I hate it when womens=pink by default (I know
that is accident not intention here).  (I have much less of an issue with
pink dominating in wider Neontribe brand, than I do in this project if you
see what I mean)

**Comment by HedgehogHolly** [comment]
I do understand what you mean with the pink and is association with women. Shall I change it to the blue for now?

**Comment by katquatermass** [comment]
Yes - I think so - if we had our overall website brand established and this
was linking through to that then I'd say keep it pink - but as we don't
lets go blue!

Kat

**Comment by HedgehogHolly** [comment]
@katquatermass new colours!

![artboard 5-100](https://user-images.githubusercontent.com/41140803/53018893-68fb4500-344b-11e9-8062-de687771c522.jpg)

![artboard 6-100](https://user-images.githubusercontent.com/41140803/53018898-6d276280-344b-11e9-8ab5-c9ef6f93b124.jpg)

**Comment by katquatermass** [comment]
I like!  Thanks

**Comment by HedgehogHolly** [comment]
Do you think I should change the design mock-up to match? as it currently uses the pink colour.

**Comment by katquatermass** [comment]
Yes- but not quite yet. Wait til I have some more folks feedback on the
icons and then we can update it with lots of things at once? eg switch
photos for illustrations, do the info page as planned.  Does that work ok
for you?

**Comment by HedgehogHolly** [comment]
Yes, that sounds like a good idea.

**Comment by katquatermass** [comment]
This is my latest work on the blog post. On Monday first thing I'd like to send it out as a pdf to one of the orgs we're probably working with. @HedgehogHolly could you tidy it up design wise for its PDF version
@harryharrold and @roseb04 (or anyone else) if either of you can look before @HedgehogHolly has time to look at it (set a time for them please @HedgehogHolly !) then I'd appreciate it. 

If no one has time we can go with this version just for this one organisation and do copy improvements for the blog later.

https://docs.google.com/document/d/1aqMG1h199DH7WWKqkvV59PhEO8fh01uvt0hl1mWhZIk/edit?usp=sharing

**Comment by rosejbon** [comment]
@katquatermass I have just had a read it it looks good to me, I've made one comment on the doc. Do we want a call to action on the end? Something like:

> If you would like to know more about this project you can email us at contemplatingaction@neontribe.co.uk

**Comment by katquatermass** [comment]
Once it is a blog post the calls to action will be up the top and we should
repeat at the end - its links to the demo app and the survey I think rather
than email for more. Right now it might be as one of our possible 3
charities  we look forward to speaking with you soon! The pdf won't be used
as a cold contact - its a pre-meeting thing for Target Ovarian Cancer (and
Norwich Mind if you think it is helpful for them)

Kat

**Comment by rosejbon** [comment]
That makes sense! And, yes, I think it would definitely be helpful to send over to Norwich Mind, I covered a bit of what you said in my email/discussion with people, but not much around the history and who is funding the project or our future plans.

**Comment by HedgehogHolly** [comment]
@katquatermass I have changed the images to ones that use Poppins typeface (as they were still in Monesterrat) and the document typeface to tie it in with the images/app. 

I've made some aesthetic changes to the document as well, changing the margins, the bullet points and the list of the pattern. I've also split the document up - which if you don't think it works/flows well it can easily be changed, it's just with the images being larger and margins changed it ended up with just the second point/step and "We’re looking forward to discussing the Test and Learn project with you" being on their own on the third page and it looked odd/empty

**Comment by katquatermass** [comment]
I like all your changes for the PDF. I have resaved it here https://docs.google.com/document/d/1I_lsaHHjRuFFMNHA_VlwcqPio7yK2eZI_4zE7iPxoXU/edit?usp=sharing

The other version for the blog, I think we will need to revert - because I put long alt-text copy in the images and then forgot to tell you it was there, and I'd like to grab it for the new images. But that can wait til Monday!

**Comment by katjam** [comment]
@katquatermass @HedgehogHolly It's awesome! Pleasure working with such a great team.
