### ISSUE TITLE
Exit site link

### ISSUE THREAD

**Issue by KingFruit85** [neontribe/contemplating-action#250]
## Description
When clicking the exit site button, a second tab is opened. both original tab and the newly opened tab redirect to google.com.

I assume this isn't the intended behaviour.

## Steps to reproduce
1. navigate to https://neontribe.github.io/contemplating-action/
1. Click the "Exit Site" button at the top right of the screen

## Platform (if relevant)
Tested in Edge 17.17134 & Chrome 77.0.3865.90

## Proposed fix

I believe removing the following code from the button fixes this behaviour:

`target="_blank" rel="noopener"`

**Comment by katjam** [comment]
@KingFruit85 Thank you for your bug report.

For this app, it is the intended behaviour so that if the back button pressed on the current tab, the user will not get back to the site.

We talked a lot about how to make this safest. One idea was to populate the history with junk in between but never had time to implement.

The Exit feature also isn't used in our most recent versions of the Contemplating Action sites. We do use it on one of our other sites though so if you have a neat solution, we'd love to hear.
