### ISSUE TITLE
Illustrations for the info (demo) version

### ISSUE THREAD

**Issue by katjam** [neontribe/contemplating-action#27]
## Description
Illustrate the starter story. Blocked by https://github.com/neontribe/contemplating-action/issues/13

## Plan
- [ ] TBC

**Comment by katquatermass** [comment]
Here is the copy for the main "explain how it works story"  - it's got ideas for the "explain how it works story illustration in"  https://docs.google.com/document/d/15jgy6AT6OFcZ98N4nHDvDxHB9nZpvuDfRXPdZuHQAzo/edit?usp=sharing

@HedgehogHolly   for once I think my explanation might actually be clear on reading, but if not I can do a call early afternoon...

**Comment by HedgehogHolly** [comment]
This is a **work in progress** for the demo illustrations. More detail and texture will be added, but it would be good to get people's opinions on the theme/concept of the illustrations and wether they fit with Kat's copy.



**Part 1 of 4** - The story starts with some background. It gives us key pieces of information that make this person’s story clear and relatable. It tends to deal with facts about the situation they were in rather than their feelings. It is always a situation that clearly needed to change.


![artboard 1-100](https://user-images.githubusercontent.com/41140803/52644148-30e98480-2ed6-11e9-9249-ec723f1b0938.jpg)


**Part 2 of 4** - Next the story moves on a little. It does one of two things. Either it tells us about a specific incident that began a drive to change things, or it explores the person’s fears and things that were holding them back. This section focuses on emotions and helps us connect with the person’s story.

![artboard 2-100](https://user-images.githubusercontent.com/41140803/52644155-347d0b80-2ed6-11e9-8107-159bed51f78b.jpg)


**Part 3 of 4** - Here the story starts to change for the better. The person becomes able to take a positive step towards change. The story tells us a little about what happened, how they managed to take the step and how they felt. 

![artboard 3-100](https://user-images.githubusercontent.com/41140803/52644160-3646cf00-2ed6-11e9-9162-24d0a83cec9a.jpg)


**Part 4 of 4** - The final section of the story is about hope. It show that making a chance can be a positive choice. However it doesn’t suggest that the person’s life is now perfect. It is designed to encourage others to believe they could make a move to a more hopeful place too. It takes care not to sound out of reach.

![artboard 4-100](https://user-images.githubusercontent.com/41140803/52644165-38109280-2ed6-11e9-9078-cb49ffc4e7e6.jpg)

**Comment by katjam** [comment]
@HedgehogHolly These look great so far.

**Comment by HedgehogHolly** [comment]
Updated illustrations

![artboard 1 copy-100](https://user-images.githubusercontent.com/41140803/52729196-a32e9780-2fb0-11e9-9659-af4a38af192d.jpg)
![artboard 2 copy-100](https://user-images.githubusercontent.com/41140803/52729197-a3c72e00-2fb0-11e9-987f-e14570bb6c35.jpg)
![artboard 3 copy-100](https://user-images.githubusercontent.com/41140803/52729198-a3c72e00-2fb0-11e9-95df-b7b62e670d36.jpg)
![artboard 4 copy-100](https://user-images.githubusercontent.com/41140803/52729200-a3c72e00-2fb0-11e9-9236-27a702e8ab17.jpg)

**Comment by katquatermass** [comment]
These are sooo good!

**Comment by katjam** [comment]
:heart:
