### ISSUE TITLE
Survey to test info version against metrics

### ISSUE THREAD

**Issue by katjam** [neontribe/contemplating-action#28]
## Description
Validation of metrics measurement against info (demo) version

## Plan
- [ ] Using #7 design a survey
- [ ] Run the survey

**Comment by katquatermass** [comment]
@HedgehogHolly in advance of us knowing what questions we actually want to ask, could you (possibly with Rose's help) start looking at Typeform and what it allows us to do design wise? I don't think that actually it is that much  but it would be good to know.
Here is an example of how cast are using a landing page plus typeform in a way we might consider for this project (I think) Although the landing page would need three links - the app, the survey, and a blog (Maybe not as a link, maybe on scroll down....

https://amber.wearecast.org.uk/

**Comment by HedgehogHolly** [comment]
I spoke to Rose about Typeform. We believe the initial landing page that cast have isn't part of typeform, its only when you click on 'Help shape this service' that it takes you to the typeform landing page. It doesn't seem possible to have multiple buttons on that landing page, you can only have one that takes you to the form/survey. So if you want the three buttons or some kind of long scroll, we would need to create a stand alone page outside of typeform.

**Comment by katquatermass** [comment]
Understood. I think that one is over to @Katja Mordaunt
<katja@neontribe.co.uk> then as a question on how we integrate the app, a
single landing page (and possible blog post) and the survey.
Could be done from a wordpress theme and look as good as that CAST one. but
I suspect we might have a cleverer solution

**Comment by katquatermass** [comment]
Draft is here for viewing https://addaction-quiz.typeform.com/to/zUOTYA

**Comment by katquatermass** [comment]
#7 has been updated by metric thinking that I want to discuss with CAST

**Comment by katquatermass** [comment]
@roseb04 to look at questions, see if you can tighten up wording anywhere, see if you think my 15 minute including app browsing time is correct

**Comment by katquatermass** [comment]
@HedgehogHolly to add styling to match app branding

**Comment by katquatermass** [comment]
@roseb04 I want to add a question logic to the email address so that people who give us emails also get the option for us to pass them to CAST... can't work out if typeform understands is not null or if I need a yes no question for logic and then the email address?

**Comment by roseb04** [comment]
@katquatermass I've gone through and edited the logic a bit and added a thank you page (that you may want to change). I've also edited the email bit to a yes/no answer and once they select yes they will be asked to provide their email. 

I think the text is fine. It is hard to make shorter, but because of the audience I think it is a reasonable assumption that they are more likely to spend a little more time reading.

Quick question, are we assuming that answering the survey is the last thing people will do, only once they have browsed the app? If so then the survey should only take 5 minutes. If not I think we should add some text explaining that people should view the app and understand the project before they complete the survey.

**Comment by rosejbon** [comment]
@katquatermass I've had a look and it looks good. Done a few things

- Changed the email flow, people are asked a yes/no question then given the option to provide their emails
- Added a thank message, the text of which you may want to alter
- I think the length of the text is fine. I feel like shortening it would be hard and given the audience it may be a fair assumption that they are likely to be ok reading a bit more

Also, I had a few questions: 

- Is the survey the last thing people would do? Or will people be linked to the survey but not have read about the project on either via our blog or the app? If so should we say that people should view the app before completing the survey? (I think the survey should only take 5 minutes)
- I think it may be better to use groups rather than statements to separate the questions. It flows a bit easier, I can quickly do this on Monday if you are happy

**Comment by katquatermass** [comment]
@roseb04 could you go ahead with grouping questions please and removing statements. (I saw it as an option but failed to make it work).  Then I'll do the next pass on copy and details

**Comment by rosejbon** [comment]
@katquatermass I've created groups and also made one tweak to the copy.

**Comment by katjam** [comment]
Done.
