### ISSUE TITLE
Rough timeline

### ISSUE THREAD

**Issue by katjam** [neontribe/contemplating-action#4]
- [x] Notes in wiki
- [x] Milestones
- [ ] Budget days inc Kimai

**Comment by katquatermass** [comment]
This is very very broadly in the wiki - I'm thinking we should do a week by week from this week onwards - do you want to start or shall I?

**Comment by katjam** [comment]
Not sure I never managed to speak to @harryharrold about which one of us should lead the project. I'm happy to carry on as we are as long as the ball doesn't get dropped. You probably have a better idea of what deliverables CAST are expecting and when, but I could also take a stab at a plan.

Shall we incorporate a weekly catchup - to keep it moving forward?

**Comment by katquatermass** [comment]
Yes. Catch ups sound good. No reason why we can't lead different bits to
make it work I guess

**Comment by katjam** [comment]
I guess we wit until we hear on finding. But we should do something a bit more granular with delivery dates for some elements.

**Comment by katjam** [comment]
@katquatermass Once you and @harryharrold have confirmed the budget/ day allocation let's have a meeting and make a rough timeline with deadlines for people so they know what is expected by when and who is responsible. Chat next week? Including @roseb04  & @HedgehogHolly & @Nikomus?

**Comment by katquatermass** [comment]
Yes, sounds good to me
Kat

**Comment by katjam** [comment]
Do you want to set a day/time for it? When are you likely to have confirmation from CAST?

**Comment by katquatermass** [comment]
We have confirmation from CAST - sorry only got as far as saying that in
Slack not here.   Meeting time to suit you Monday?

**Comment by katjam** [comment]
After 10:30 I think I'm flexible. @harryharrold said this morning that you hadn't got the shape of the project confirmed yet... maybe that has happened since?

**Comment by katquatermass** [comment]
I'll check that. I thought we had
Confirm Monday.
Kat

**Comment by katjam** [comment]
![image](https://user-images.githubusercontent.com/861172/52278253-85c55200-294e-11e9-98d6-3488d5e8b15b.png)

**Comment by katquatermass** [comment]
Phases of work to block in (I think):
1. Blog post/ pdf/ visual overview of project: WHO: Kat and Holly w little time from Rose WHEN:
2. Copy for info version of app: WHO Kat WHEN:
3. Design for info version of app: WHO Holly
4. Illustrations for info version of app: WHO Holly (dependent on 2)
5. Code for info version of app: WHO Nick? Katja? (dependent on 2,3,4)
6. Metrics plan for reactions to info version: WHO Katja?   
7. Survey to test info version against those metrics: WHO (dependent on 6)
8. Approach to charities for workshops and own app (I see this as separate to the survey, rather than dependant on it): WHO:      (dependent only on 1)
9. Workshops with charities to explore fears and barriers and plan stories: WHO    MUST BE EARLY MARCH, (dependent on 1-8)
10. Collect and illustrate stories      MUST BE MID MARCH (dependent on 1-9)
11. Charity versions of App coded late march  -  testing is in April

**Comment by katquatermass** [comment]
https://docs.google.com/spreadsheets/d/1s1kQOMbH9uKZoNxnmDwLptundjwDpBYO3UvCfgQ9xag/edit#gid=0

**Comment by katjam** [comment]
https://github.com/neontribe/contemplating-action/wiki/Phase-1-rough-timeline-(finish-March-2019)
