### ISSUE TITLE
Configurable info (e.g. call to action, email and Stories links)

### ISSUE THREAD

**Issue by katjam** [neontribe/contemplating-action#51]
## Description
Title, contact email, link to stories, call to action (TBC)

## Plan
- [x] Agree text (in #13 maybe)
- [x] Replace in Views/Config.elm https://github.com/neontribe/contemplating-action/pull/59
- [x] Hack into views - once happy with what we need to configure per brand, we can pull functions into Config
- [x]  Call to action (phone number in Haven's case) is going to be survey link in this version? We will create a CTA module (or export in Config) for this to differ in other versions.
- [x] Add link to survey https://contemplating-action.typeform.com/to/zUOTYA

## Acceptance Criteria
- [x] Verify new copy for the survey link is appearing in right places
- [ ] @katquatermass sign off on copy in situ

**Comment by katjam** [comment]
@katquatermass  We've been looking at the compatibility of the content with the existing app and think the most straightforward thing to do is swap the Phone Number (which is Haven's main call to action) for the survey link (which is our main call to action) 

The format we offer charities is then - One call to action and one means of contact. (could be phone and a chatline - like Haven) or (Survey and an email - like this version)

Does that sounds like a reasonable approach?

**Comment by katquatermass** [comment]
Yes. I think that is a good approach!   Interestingly one of the "ways that early research is showing that a reusable app is difficult" is "charities can't decide which of their support services should receive the call to action!

**Comment by katquatermass** [comment]
@roseb04 could you have a look in typeform - currently the survey link is displaying with addaction in the title... can we configure it to something relevant to give to Katja to use?

**Comment by rosejbon** [comment]
Yeah no probs, I will have a look at it :)

**Comment by rosejbon** [comment]
@katquatermass I've changed the url. It now says https://contemplating-action.typeform.com/to/zUOTYA

**Comment by katjam** [comment]
Thanks. @Nikomus is looking into embedding the survey. #73

**Comment by rosejbon** [comment]
@Nikomus I've copied the code to embed the survey on a full page:
```<html> <head> <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=0"> <title>Contemplating Action</title> <style type="text/css"> html{ margin: 0; height: 100%; overflow: hidden; } iframe{ position: absolute; left:0; right:0; bottom:0; top:0; border:0; } </style> </head> <body> <iframe id="typeform-full" width="100%" height="100%" frameborder="0" src="https://contemplating-action.typeform.com/to/zUOTYA"></iframe> <script type="text/javascript" src="https://embed.typeform.com/embed.js"></script> </body> </html>```

I copied it from the embed functionality on Typeform. Don't know if this is helpful

**Comment by jermyk** [comment]
## Acceptance Criteria
- [x] Verify new copy is appearing in right places
- [ ] @katquatermass sign off on copy in situ

**Footer**
Copy doc says  - Developed by Neontribe
Footer says - © 2017 - neontribe.co.uk

**Stories**
Copy doc says - Our Project Story
Page says - Our Project

Copy doc says - The Haven Story
Page says - A Haven Story

Copy doc says - Button: I’d like to know more
Page says - Link - See our Project's Story

Copy doc says -  Button: Read X’s Story
Page says - Link - See The Haven's Story

Part 1 of 4

Copy doc  - ""Doesn't have speech marks in text""
The story starts with some background. It gives us key pieces of information that make this person’s story clear and relatable. It tends to deal with facts about the situation they were in rather than their feelings. It is always a situation that clearly needed to change.

Page says - 
"The story starts with some background. It gives us key pieces of information that make this person’s story clear and relatable. It tends to deal with facts about the situation they were in rather than their feelings. It is always a situation that clearly needed to change. "   
**Copy Issues**
![Screenshot_032719_115013_AM](https://user-images.githubusercontent.com/4446325/55073768-7b8a1f00-5086-11e9-9178-8566135f25ea.jpg)

**Same applies for part 2 3 & 4**

**Buttons**
Copy doc says - Bite size information
Page says -  I'd like some other information

Copy doc says - What is the survey?
Page says - Take part in our survey

**Comment by jermyk** [comment]
@katquatermass 

Please see above where there are some discrepencies.

**Comment by katjam** [comment]
@katquatermass to go through copy concerns.

**Comment by katquatermass** [comment]
Closing - created cards OR updated copy document to reflect what is in app, where this is acceptable
