### ISSUE TITLE
Early thinking around measuring success

### ISSUE THREAD

**Issue by katjam** [neontribe/contemplating-action#7]
## Metrics plan to use against the info (demo) version

We should be thinking about this from the start.

Might be informative - can't remember exactly but I think it will be useful watch:
https://drive.google.com/drive/folders/1sDXfceaIuFedKsh4_Qvnv8PLiHtpzP8E

**Comment by katquatermass** [comment]
Some thoughts:

Setting targets will be hard - because the sector doesn't have good conversion  baselines so doesn't really know what good or bad looks like. BUT if we measure success on the concept of "being able to provide some future baselines" for a) social media reach generated in relation to the journey b) conversions from that reach and c) conversions all the way to helpline    that might be good?

So within the project we'd be looking at comparing each intervention to others and to any external projects that we pick up comparable data for along the way

**Comment by katquatermass** [comment]
Our survey has different sections:

Section 1) About the organisations - for interest, we want to see the range of organisations represented, we have no particular goals
Section 2) About the concept, the problem we are trying to solve being universally recognised - we want to see 80% of respondents agreeing or strongly agreeing with the statements 
Section 3) About the particular solutions. " a majority of broadly positive statements needed in order to take the project further" would be a good overall success. However we can still progress even if there is only a particular segment of charities showing interest and therefore feedback is less positive.
Section 4) These are research - there is no goal here - but the overview (and if we got a big enough sample - some cuts of it with various organisational data) is going to be a useful temperature test and helpful for organisations to bear in mind

Overall response rate: We should be aiming for 20% of any directly targeted folk to respond. However we will also be doing some broad brush reach where we won't know what the longest tail is like (twitter, newsletters)
